"""GitHub_Agent implementation using the terminal tool.

This module intentionally avoids importing ``delegate_task``.  It is meant
to be invoked from an orchestrator/runtime that already has tool access.
"""

from __future__ import annotations

import json
import os
from typing import Any, Callable, Dict, Optional

from multi_agent_builder.agents import github as github_agent
from multi_agent_builder.schemas import BuildState


DEFAULT_GIT_IGNORE = """\
__pycache__/
*.pyc
.venv/
.env
.hermes/
dist/
build/
.idea/
.vscode/
.DS_Store
"""

DEFAULT_README_TEMPLATE = """\
# {project_name}

Generated by Hermes Universal Multi-Agent Builder.

## Overview
{user_request}

## Getting Started
{getting_started}
"""

DEFAULT_LICENSE = """\
MIT License

Copyright (c) {year}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction...
"""


def _run_git(
    *args: str,
    terminal: Callable[..., Dict[str, Any]],
    cwd: Optional[str] = None,
) -> Dict[str, Any]:
    command = "git " + " ".join(args)
    try:
        result = terminal(command=command, workdir=cwd, timeout=180)
        out = result.get("output", "")
        err = result.get("error")
        rc = result.get("exit_code", 0)
        return {"command": command, "stdout": out, "stderr": err or "", "exit_code": rc}
    except Exception as exc:
        return {"command": command, "stdout": "", "stderr": str(exc), "exit_code": 125}


def run_github_agent(
    state: BuildState,
    repo_config: Dict[str, Any],
    github_repo_url: str,
    terminal: Callable[..., Dict[str, Any]],
    write_file: Callable[..., Dict[str, Any]],
    workdir: Optional[str] = None,
) -> Dict[str, Any]:
    if state.code is None or state.audit is None:
        raise ValueError("state.code and state.audit must be populated before GitHub agent")

    root = workdir or os.getcwd()

    report: Dict[str, Any] = {
        "repo_url": github_repo_url,
        "branch": "main",
        "commit_hash": None,
        "steps": [],
        "ok": False,
    }

    report["steps"].append(_run_git("init", terminal=terminal, cwd=root))
    report["steps"].append(_run_git("checkout -b main", terminal=terminal, cwd=root))

    for path, content in state.code.items():
        target = os.path.join(root, path)
        os.makedirs(os.path.dirname(target), exist_ok=True)
        try:
            write_file(path=target, content=content)
            report["steps"].append({"file": path, "ok": True})
        except Exception as exc:
            report["steps"].append({"file": path, "ok": False, "error": str(exc)})

    gitignore_path = os.path.join(root, ".gitignore")
    if not os.path.exists(gitignore_path):
        try:
            write_file(path=gitignore_path, content=DEFAULT_GIT_IGNORE)
            report["steps"].append({"file": ".gitignore", "ok": True})
        except Exception as exc:
            report["steps"].append({"file": ".gitignore", "ok": False, "error": str(exc)})

    readme_path = os.path.join(root, "README.md")
    try:
        readme = DEFAULT_README_TEMPLATE.format(
            project_name="builder-project",
            user_request=state.user_request,
            getting_started="See project files for setup instructions.",
        )
        write_file(path=readme_path, content=readme)
        report["steps"].append({"file": "README.md", "ok": True})
    except Exception as exc:
        report["steps"].append({"file": "README.md", "ok": False, "error": str(exc)})

    report["steps"].append(_run_git("add", ".", terminal=terminal, cwd=root))
    commit_msg = f"chore(builder): init project for {state.user_request}"
    commit = _run_git("commit", "-m", commit_msg, terminal=terminal, cwd=root)
    report["steps"].append(commit)

    if commit.get("exit_code") == 0:
        stdout = commit.get("stdout", "") or ""
        last_line = stdout.splitlines()[-1] if stdout else ""
        # Typical git output: "main branch commit <hash>" or just "<hash>"
        report["commit_hash"] = last_line.split()[-1] if last_line.split() else None
        report["ok"] = True

    report["steps"].append(_run_git("remote", "add", "origin", github_repo_url, terminal=terminal, cwd=root))
    push = _run_git("push", "-u", "origin", "main", terminal=terminal, cwd=root)
    report["steps"].append(push)
    report["ok"] = report["ok"] and push.get("exit_code") == 0

    return report
